services:
  - type: web
    name: pelada-oficial-api
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 14692725836-8n7a4aisfk1sjmvadnn400joq1j6rjdi.apps.googleusercontent.com
