spring.application.name=Pelada Oficial

# Servidor na porta 8080
server.port=8080

# Conexão com PostgreSQL (docker compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/pelada_oficial
spring.datasource.username=pelada
spring.datasource.password=pelada123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
