spring.application.name=Pelada Oficial
server.port=8080

# Por enquanto usa H2 (banco em memória) para o IntelliJ subir sem erro.
# Quando o PostgreSQL estiver configurado, troque para: postgres
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
