package br.com.peladaoficial.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Garante colunas novas em produção (Neon) quando ddl-auto=update não aplicou a tempo.
 */
@Component
public class SchemaPatchRunner implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(SchemaPatchRunner.class);

    private final JdbcTemplate jdbc;

    public SchemaPatchRunner(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public void run(ApplicationArguments args) {
        try {
            jdbc.execute("""
                ALTER TABLE jogadores
                ADD COLUMN IF NOT EXISTS apto boolean NOT NULL DEFAULT true
                """);
            log.info("Schema OK: coluna jogadores.apto verificada");

            jdbc.execute("""
                ALTER TABLE eventos_partida
                ADD COLUMN IF NOT EXISTS client_lance_id varchar(80)
                """);
            try {
                jdbc.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS uk_evento_partida_client_lance
                    ON eventos_partida (partida_id, client_lance_id)
                    WHERE client_lance_id IS NOT NULL
                    """);
            } catch (Exception ignored) {
                // H2 pode não aceitar índice parcial
            }
            log.info("Schema OK: coluna eventos_partida.client_lance_id verificada");

            jdbc.execute("""
                ALTER TABLE eventos_partida
                ADD COLUMN IF NOT EXISTS assistencia_id bigint
                """);
            log.info("Schema OK: coluna eventos_partida.assistencia_id verificada");

            jdbc.execute("""
                ALTER TABLE elenco_jogadores
                ADD COLUMN IF NOT EXISTS apto boolean NOT NULL DEFAULT true
                """);
            log.info("Schema OK: coluna elenco_jogadores.apto verificada");

            jdbc.execute("""
                ALTER TABLE usuarios
                ADD COLUMN IF NOT EXISTS google_id varchar(64)
                """);
            try {
                jdbc.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS uk_usuarios_google_id
                    ON usuarios (google_id)
                    WHERE google_id IS NOT NULL
                    """);
            } catch (Exception ignored) {
                // H2 / índice parcial
            }
            try {
                jdbc.execute("ALTER TABLE usuarios ALTER COLUMN senha_hash DROP NOT NULL");
            } catch (Exception ignored) {
                // já nullable ou dialeto diferente
            }
            log.info("Schema OK: colunas usuarios.google_id / senha_hash verificadas");

            jdbc.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS plano varchar(20) DEFAULT 'GRATIS'");
            jdbc.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS plano_expira_em timestamp");
            jdbc.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS trial_inicio timestamp");
            jdbc.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS pagamento_origem varchar(20)");
            jdbc.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ultimo_pagamento_mp varchar(80)");
            jdbc.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS mp_preapproval_id varchar(80)");
            log.info("Schema OK: colunas usuarios.plano / trial verificadas");

            jdbc.execute("""
                CREATE TABLE IF NOT EXISTS caixa_config (
                    id bigint generated by default as identity primary key,
                    usuario_id bigint not null unique,
                    valor_mensal numeric(10,2) not null default 0,
                    valor_avulso numeric(10,2) not null default 0
                )
                """);
            jdbc.execute("""
                CREATE TABLE IF NOT EXISTS caixa_jogadores (
                    id bigint generated by default as identity primary key,
                    usuario_id bigint not null,
                    chave varchar(90) not null,
                    nome varchar(80) not null,
                    goleiro boolean not null default false,
                    modalidade varchar(12) not null default 'AVULSO'
                )
                """);
            try {
                jdbc.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS uk_caixa_jogador_chave
                    ON caixa_jogadores (usuario_id, chave)
                    """);
            } catch (Exception ignored) {
                /* índice já existe ou dialeto diferente */
            }
            jdbc.execute("""
                CREATE TABLE IF NOT EXISTS caixa_lancamentos (
                    id bigint generated by default as identity primary key,
                    usuario_id bigint not null,
                    jogador_id bigint not null,
                    competencia varchar(7) not null,
                    tipo varchar(12) not null,
                    valor numeric(10,2) not null default 0,
                    criado_em timestamp not null default now(),
                    nota varchar(80)
                )
                """);
            try {
                jdbc.execute("""
                    CREATE INDEX IF NOT EXISTS idx_caixa_lanc_usuario_comp
                    ON caixa_lancamentos (usuario_id, competencia)
                    """);
            } catch (Exception ignored) {
                /* índice já existe */
            }
            log.info("Schema OK: tabelas da caixa verificadas");
        } catch (Exception e) {
            // H2 em alguns modos pode não aceitar IF NOT EXISTS da mesma forma — não derruba o app
            log.warn("Não foi possível garantir colunas de schema: {}", e.getMessage());
        }
    }
}
